---
name: Container Image CI

"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Container image
        run: |
            docker build .
                --file Containerfile
                --tag instruct-lab-nvidia-container:$(date +%s)
